### ISSUE TITLE
3rd edition of  distributed systems is available by tanenbaum and van steen.

### ISSUE THREAD

**Issue by nilsocket** [theanalyst/awesome-distributed-systems#12]
Distributed Systems 3.01 Edition
by Maarten van Steen (Author),‎ Andrew S. Tanenbaum (Author)
is available,
here is the [link](https://www.amazon.com/Distributed-Systems-Maarten-van-Steen/dp/1543057381/ref=pd_sbs_14_1?_encoding=UTF8&pd_rd_i=1543057381&pd_rd_r=8MAW8997M5KBTE635SS1&pd_rd_w=3FKAW&pd_rd_wg=m6kkx&psc=1&refRID=8MAW8997M5KBTE635SS1)

Digital version is also available for free on, book site, after providing email, we get the link to download the latest version of book for free.
[Book site](https://www.distributed-systems.net/index.php/books/distributed-systems-3rd-edition-2017/)

**Comment by nilsocket** [comment]
No, You can just add it.
Thank You.

**Comment by eroberto88** [comment]
Thank you. This book is very useful.

**Comment by theanalyst** [comment]
closed via #32

**Comment by pratham5368** [comment]
it is closed

**Comment by WeihanLi** [comment]
The link is not working now

here's the 4th edition link
https://www.distributed-systems.net/index.php/books/ds4/
